{% set name = "graphql-core" %}
{% set version = "2.3.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 74a8f509ae8c4a58271f5d6b46d5c75b4aed116821ab62dea252d8041bfe057a

build:
  noarch: python
  number: 0
  script:
    - "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six >=1.10.0
    - promise >=2.3,<3
    - rx >=1.6,<2

test:
  imports:
    - graphql

about:
  home: https://github.com/graphql-python/graphql-core
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A Pythonport of the GraphQL.js reference implementation of GraphQL.'

extra:
  recipe-maintainers:
    - pmlandwehr
    - carlodri
    - bollwyvl
